### PR TITLE
refactor: repurpose the repo to clarity-vscode

### LINKED ISSUE #22: Remove unused code
After switching to using `clarinet lsp`, there is a good bit of unused code in this repo that needs to be cleaned up.

### LINKED ISSUE #91: Remove unused code
After switching to using `clarinet lsp`, there is a good bit of unused code in this repo that needs to be cleaned up.

### PR DESCRIPTION
**Pull request by hugoclrd**
This PR fixes hirosystems/clarity-lsp#22.

- [x] Move all the Code extension to the root of the repo
- [x] Clean all the LSP / rust code
- [x] Rework JS/TS code quality 
  - [x] Remove TSLint and typescript-formatter in favor of eslint / prettier only
  - [x] Apply the new config on every TS files
  - [x] Remove unused dependencies
  - [x] Upgrade some devDepencies

### CODE REVIEW

**Review by obycode — CHANGES_REQUESTED** [review]
The bulk of the changes look good to me. Can you do some more work on launch.json to get everything working? I run into a bunch of issues there.

**Comment by hugocaillard** [comment]
@obycode 
Just pushed the changes we discussed.

As you suggested, I added an "npm install" (actually "npm ci" which can be slightly faster) task that will run before the build. So that someone could literally clone the repo and press the green button.

Only drawback I see it that "npm ci" will run every time. Even though it only takes a few seconds, it  could be bothering compared to just run `$ npm install` once, after cloning the project.

Let me know what you think

**Comment by obycode** [comment]
I think that's fine that `npm ci` runs every time. Like you said its quick, and it will be worth it to avoid the problems if it doesn't run.

The LSP seems to be working well, but the debugger doesn't seem to be working for me. I don't see debug.js in out/, so it looks like that step might've been missed? I can dig a little deeper later.

**Comment by hugocaillard** [comment]
@obycode Looks like `npm build` (or just `tsc`) doesn't build `out/debug.js`, even on the develop branch. 
We could had a build-debug step. I'll had that in an upcoming commit

**Review by obycode — APPROVED** [review]
Looks great, thanks @hugocaillard!

**Pull request merged**
